import React, { useState } from 'react';
import Head from 'next/head'
import SideBar from '../components/sideBar'
import Middle from './middle';

export default function Home() {

  return (
    <div >
      <Head>
        <title>Refael Whatsapp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Middle />
    </div>
  )
}
