import React, { useState } from 'react';
import Head from 'next/head'
import SideBar from './sideBar'
import Middle from './middle';
import Login from './login';
import Link from 'next/link';

// socket.on("oneTry", () => {console.log("message from socket id: " + socket.id)});

export default () => {
  const [googleLogin, setGoogleLogin] = useState("");
  const [login, setLogin] = useState(false);
  // console.log(socket.id)

  console.log('Connecting to') 
  return (
    <div >
      {/* <Head>
        <title>Refael Whatsapp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}

      {/* {!login ? <Login login={login} setLogin={setLogin} googleLogin={googleLogin} setGoogleLogin={setGoogleLogin} /> : null} */}
      <Link href={"/"} >
        <Login />
      </Link>
      {/* <Link href={"/sideBar"} >
        <SideBar />
      </Link> */}
    </div>
  )
}
